package com.example.cmbaiwebsite.entity;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_tag.id
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_tag.article_id
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_tag.tag_id
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    private Long tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_tag.id
     *
     * @return the value of ms_tag.id
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_tag.id
     *
     * @param id the value for ms_tag.id
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_tag.article_id
     *
     * @return the value of ms_tag.article_id
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_tag.article_id
     *
     * @param articleId the value for ms_tag.article_id
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_tag.tag_id
     *
     * @return the value of ms_tag.tag_id
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_tag.tag_id
     *
     * @param tagId the value for ms_tag.tag_id
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }
}