server:
  port: 8002
spring:
  redis:
    host: localhost
    port: 6379
  application:
    name: cmb-ai-website
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
eureka:
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka

#mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      table-prefix: ms_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.cmbaiwebsite
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml










