server:
  port: 8002
spring:
  redis:
    host: localhost
    port: 6379
  application:
    name: cmb-ai-website
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
eureka:
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka

#mybatis-plus
mybatis:
  #标注mybatis配置文件的位置
  config-location: classpath:mybatis-config.xml
  #标注待解析的mapper的xml文件位置
  mapper-locations: classpath:com.example.cmbaiwebsite.mapper/*.xml
  #标注实体类位置
  type-aliases-package: com.example.cmbaiwebsite.entity

#日志文件
logging:
  level:
    com.example.cmbaiwebsite.mapper: debug
    #config: classpath:logback-spring.xml;










