package com.example.cmbaiwebsite.mapper;

import com.example.cmbaiwebsite.entity.Tag;
import com.example.cmbaiwebsite.entity.TagExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_tag
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    long countByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_tag
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    int deleteByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_tag
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_tag
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    int insert(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_tag
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    int insertSelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_tag
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    List<Tag> selectByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_tag
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    Tag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_tag
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    int updateByExampleSelective(@Param("record") Tag record, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_tag
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    int updateByExample(@Param("record") Tag record, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_tag
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    int updateByPrimaryKeySelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_tag
     *
     * @mbg.generated Mon Oct 10 16:50:07 CST 2022
     */
    int updateByPrimaryKey(Tag record);
}